### ISSUE TITLE
Streaming video only - ffmpeg was not found

### ISSUE THREAD

**Issue by DMBlakeley** [dgreif/ring#259]
# Bug Report

### Describe the Bug
 Installed ffmpeg per instructions on OS X 10.11.6 and receiving the error 

`[2/22/2020, 12:25:50 PM] [Ring] Streaming video only - ffmpeg was not found. See https://github.com/dgreif/ring/wiki/FFmpeg for details.`

### To Reproduce
 - Start Homebridge
 - Attempt to view video from Ring doorbell. Snapshot and live video are displayed correctly.
 - See error

### Expected behavior
 Video + audio would be streamed.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```
"platform": "Ring",
"refreshToken": "xxx"
```

### Environment

 - OS: OSX 10.11.6
 - Node.js: 12.14.1
 - NPM: 6.13.4
 - homebridge-ring: 7.0.0
 - homebridge: 0.4.50

**Comment by donavanbecker** [comment]
You followed the instructions on the wiki,

**Comment by DMBlakeley** [comment]
Yes, I did.  Confirmed that ffmpeg was updated in /usr/local/bin also.

**Comment by donavanbecker** [comment]
MacOS

First install HomeBrew

/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
Then install homebrew-ffmpeg

brew tap homebrew-ffmpeg/ffmpeg
brew install homebrew-ffmpeg/ffmpeg/ffmpeg --with-fdk-aac

**Comment by donavanbecker** [comment]
Try this

**Comment by DMBlakeley** [comment]
@donavanbecker, went through your recommended installation process. Appears that homebrew-ffmpeg is not compatible with OS X 10.11.6 as installation results in an error stating incompatibility with OS X 10.11.

**Comment by donavanbecker** [comment]
Then I guess you will have to upgrade to a newer macOS unless someone else has another guide?

**Comment by DMBlakeley** [comment]
It is an older Mac mini and can't be upgraded but thanks for your suggestions.

**Comment by donavanbecker** [comment]
You could use MacPorts:

```
sudo port install ffmpeg +nonfree

```

Which will ask:

--->  Computing dependencies for ffmpeg
The following dependencies will be installed: 
 libfdk-aac
 nasm
Continue? [Y/n]: y
Result:

$ ffmpeg -codecs | grep libfdk
AAC (Advanced Audio Coding) (decoders: aac aac_fixed aac_at libfdk_aac ) (encoders: aac aac_at libfdk_aac )
The other option would be to compile it yourself and choose whatever options you want.

**Comment by dgreif** [comment]
@DMBlakeley @donavanbecker I just released v`7.2.0-alpha.0`, which automatically uses the pre-built binaries from ffmpeg-for-homebridge (huge thanks to @oznu for these!).  Would you guys be able to give it a try and make sure it works on your servers?

**Comment by DMBlakeley** [comment]
Feeling like I am going in circles ... still getting error 

`[Ring] Streaming video only - ffmpeg was not found.`

Believe that I may have multiple versions of FFmpeg installed and the plug-in is not finding the correct version. Think I tracked them down but what is the preferred way to reinstall FFmpeg?

**Comment by DMBlakeley** [comment]
I decided to roll back to version 6.1.1 and FFmpeg 3.4.1. These were the versions that were working prior to trying to get audio working. This may be due to being constrained to OS X 10.11.6 (El Capitan) on my Mac mini.

I have also lost snapshots from the Ring doorbell camera which I cannot seem to get back.

**Comment by DMBlakeley** [comment]
Now working with with v6.1.1 of plug-in and FFmpeg 4.4.2 (vanilla version). Error has changed a bit to "Streaming video only - found ffmpeg, but libfdk_aac is not installed." but all my cameras are working (Ring and two NetCams).

Installed HomeBrew on my MacBook and built FFmpeg with --with-fdk-aac. This build removes error, however, libx264 support for the NetCams does not seem to work. From what I can tell libx264 should be standard.

Any thoughts?

**Comment by dgreif** [comment]
@DMBlakeley using "vanilla" ffmpeg won't work because it doesn't have the proper codec (libfdk_aac) bundled in.  If you install v`7.2.0-alpha.0`, it should "just work" because it installs and uses a pre-built version of ffmpeg that has the codec included.  Did you try `7.2.0-alpha.0`?

**Comment by DMBlakeley** [comment]
@dgreif, agree that "vanilla" 4.2.2 ffmpeg does not include libfdk_acc. Yes I did try `v7.2.0-alpha.0` which I realize installs the correct version. My problem basically is that I cannot find a version of ffmpeg which works both with the Ring doorbell and the Belkin Netcams which I have. FFmpeg with libfdk_acc support breaks the Netcams. So for the moment I am using the "vanilla" version.

**Comment by oznu** [comment]
@dgreif i think @DMBlakeley problem with the pre-compiles binaries is he's running El Captain which is a 5 year old OS.

The ffmpeg npm package tests the binary works on the system; if it failed the test on install it should return `undefined` at runtime.

@DMBlakeley can you show the logs for this install?

```
sudo npm install -g --unsafe-perm homebridge-ring@7.2.0-alpha.0
```

**Comment by DMBlakeley** [comment]
When I run above sudo command I receive the following during install:

```
Blakeleys-Mac-Mini:node_modules Blakeleys$ sudo npm install -g --unsafe-perm homebridge-ring@7.2.0-alpha.0
Password:
/usr/local/bin/ring-device-data-cli -> /usr/local/lib/node_modules/homebridge-ring/ring-device-data-cli.js
/usr/local/bin/ring-auth-cli -> /usr/local/lib/node_modules/homebridge-ring/ring-auth-cli.js

> ffmpeg-for-homebridge@0.0.1-test.17 install /usr/local/lib/node_modules/homebridge-ring/node_modules/ffmpeg-for-homebridge
> node install.js
Downloading ffmpeg from https://github.com/oznu/ffmpeg-for-homebridge/releases/latest/download/ffmpeg-darwin-x86_64.tar.gz
100% - Download Complete
dyld: Symbol not found: _kCVImageBufferTransferFunction_ITU_R_2100_HLG
  Referenced from: /Users/Blakeleys/.npm/_ffmpeg_for_homebridge/ffmpeg
  Expected in: /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
 in /Users/Blakeleys/.npm/_ffmpeg_for_homebridge/ffmpeg
An error occured while testing the downloaded ffmpeg binary.
+ homebridge-ring@7.2.0-alpha.0
added 15 packages from 6 contributors and updated 3 packages in 22.254s
```
Not sure where I find the "log" that you reference.

**Comment by DMBlakeley** [comment]
Reran install for 7.2.0-alpha.1 and found that the ring-client-api was not updated. Ran separate update and now shows where incompatibility is at. As ffmpeg is not updated the "vanilla" version is retained. Probably need to keep this version to work with OS X 10.11.6.

```
Blakeleys-Mac-Mini:node_modules Blakeleys$ sudo npm install --unsafe-perm ring-client-api@7.2.0-alpha.1
Password:

> ffmpeg-for-homebridge@0.0.1-test.17 install /Users/Blakeleys/node_modules/ffmpeg-for-homebridge
> node install.js

Downloading ffmpeg from https://github.com/oznu/ffmpeg-for-homebridge/releases/latest/download/ffmpeg-darwin-x86_64.tar.gz
100% - Download Complete
dyld: Library not loaded: /usr/local/opt/xz/lib/liblzma.5.dylib
  Referenced from: /Users/Blakeleys/.npm/_ffmpeg_for_homebridge/ffmpeg
  Reason: Incompatible library version: ffmpeg requires version 8.0.0 or later, but liblzma.5.dylib provides version 6.0.0
An error occured while testing the downloaded ffmpeg binary.
npm WARN saveError ENOENT: no such file or directory, open '/Users/Blakeleys/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/Blakeleys/package.json'
npm WARN Blakeleys No description
npm WARN Blakeleys No repository field.
npm WARN Blakeleys No README data
npm WARN Blakeleys No license field.

+ ring-client-api@7.2.0-alpha.1
added 14 packages from 6 contributors, updated 1 package and audited 1475 packages in 10.502s

1 package is looking for funding
  run `npm fund` for details

found 13 vulnerabilities (3 low, 4 moderate, 6 high)
  run `npm audit fix` to fix them, or `npm audit` for details

```

**Comment by dgreif** [comment]
@DMBlakeley thanks for providing those logs, which are exactly what @oznu was asking for.  Unfortunately you MacOS version is simply too old to support the pre-built binaries.  If you are unable to build them yourself in such a way that both Ring and Belkin Netcams, then you will have to choose one or the other (unless you are willing to move to another computer for your homebridge server).  Since all that you are missing on the Ring side is audio, I'd recommend you stick with the "vanilla" ffmpeg and keep your Belkin Netcams working as well.  I'm going to close this issue since there isn't anything else we can do from the homebridge-ring side.  Thank you for the detailed information and for your patience along the way.  Good luck!

**Comment by DMBlakeley** [comment]
Understand. Any thoughts why snapshots have stopped working? I recycled the power to the Ring (removed battery and killed power). Still no snapshots.

**Comment by dgreif** [comment]
@DMBlakeley sorry, no additional thoughts on the snapshots issue.  Wish they were more reliable, but the Ring api is really weird in some areas and this is definitely one of them.

**Comment by DMBlakeley** [comment]
Interestingly, snapshots seem to work when I am out of the house but not when I am on the local network. Also iOS more consistent than the Home app on Mac. Not a big deal as you can always just go to live view.

**Comment by dgreif** [comment]
That sounds like an issue on the HomeKit side.  I have seen/heard a lot of issues with snapshots and video getting lost when hopping from your homebridge server to your Home Hub (apple tv, iPad, HomePod), then to the outside network.  Usually being on the same network is when it works _best_, but weird things happen.  I'd recommend making sure your Home Hub is on the latest version of firmware, and the same for your Mac.

**Comment by DMBlakeley** [comment]
I have 2 Apple TVs and a HomePod that can act as the Home Hub and I keep their firmware up to date. The Apple TVs are on ethernet and HomePod on wireless. The "connected" Home Hub shifts between the 3 devices. Wish there was a way to fix or set a priority for the "connected" Hub to remove a variable when trying to troubleshoot these things.

**Comment by mjehrhart** [comment]
Hey I have an older version of macOS 11.6.5 which I forced me to  spend a while to get ffmpeg on the computer.  Had to use macports to get it because homebrew said my computer was too old. But the homebridge log files still says "Streaming video only - ffmpeg was not found. See https://github.com/dgreif/ring/wiki/FFmpeg for details."  Where does the code look for ffmpeg - what's the path it needs (/usr/local/bin maybe)?  Could I do a symbolic link for it?  that's my plan if it works.

**Comment by tsightler** [comment]
The link you posted instructs that you can set the ffmpegPath config option to point to a custom ffmpeg, and this config option is also described completely in the [Optional Parameters](https://github.com/dgreif/ring/tree/main/packages/homebridge-ring#optional-parameters) section of the readme.  Did you set this parameter?
