### ISSUE TITLE
Plugin error after update to 11.0.0: Cannot find module 'timers/promises'

### ISSUE THREAD

**Issue by rachedamer** [dgreif/ring#931]
I just updated the homebridge-ring plugin to 11.0.0. It was working fine before. Now, when I load homebridge, I get the following error: 

[10.5.2022, 19:55:12] ====================
[10.5.2022, 19:55:12] ERROR LOADING PLUGIN homebridge-ring:
[10.5.2022, 19:55:13] Error: Cannot find module 'timers/promises'
Require stack:
- /usr/lib/node_modules/homebridge-ring/node_modules/@koush/werift/lib/ice/src/ice.js
- /usr/lib/node_modules/homebridge-ring/node_modules/@koush/werift/lib/ice/src/index.js
- /usr/lib/node_modules/homebridge-ring/node_modules/@koush/werift/lib/webrtc/src/index.js
- /usr/lib/node_modules/homebridge-ring/lib/api/streaming/peer-connection.js
- /usr/lib/node_modules/homebridge-ring/lib/api/streaming/streaming-connection-base.js
- /usr/lib/node_modules/homebridge-ring/lib/api/streaming/webrtc-connection.js
- /usr/lib/node_modules/homebridge-ring/lib/api/ring-camera.js
- /usr/lib/node_modules/homebridge-ring/lib/api/location.js
- /usr/lib/node_modules/homebridge-ring/lib/api/api.js
- /usr/lib/node_modules/homebridge-ring/lib/api/index.js
- /usr/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js
- /usr/lib/node_modules/homebridge-ring/lib/homebridge/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:101:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-ring/node_modules/@koush/ice/src/ice.ts:11:1)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
[10.5.2022, 19:55:13] ====================

### Environment

 - OS: Raspbian Bullseye (completely updated)
 - Node.js: v14.19.2
 - NPM: 6.14.17
 - homebridge-ring: 11.0.0
 - homebridge: 1.4.1

**Comment by dgreif** [comment]
Update to node 16.  Please search existing issues for similar errors in the future 😉
