### ISSUE TITLE
Error loading plugin "homebridge-ring"

### ISSUE THREAD

**Issue by tonymutschler** [dgreif/ring#1096]
# Bug Report

### Describe the Bug
 A clear and concise description of the problem...
I just updated to version 11.5.0 and now i keep getting the following error

11/13/2022, 3:37:13 PMRing BridgeWARNINGNo plugins installed.
11/13/2022, 3:37:13 PMRing BridgeLoading 1 platforms...
11/13/2022, 3:37:13 PMRing BridgeBridge is running on port 51826.
11/13/2022, 3:39:01 PMringbridge stopping
11/13/2022, 3:39:06 PMRing Bridge starting
11/13/2022, 3:39:24 PMRing BridgeERRORError loading plugin "homebridge-ring"
11/13/2022, 3:39:24 PMRing BridgeWARNINGNo plugins installed.
11/13/2022, 3:39:24 PMRing BridgeLoading 1 platforms...
11/13/2022, 3:39:25 PMRing BridgeBridge is running on port 51826.

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: [e.g 6.0.3]
 - homebridge: [e.g. 0.4.50 or N/A]
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
There isn't much in the logs. Can you try removing and reinstalling the plugin?

**Comment by AppleMac1976** [comment]
Currently experiencing this issue as well after updating to 11.5.0 @dgreif

**Comment by gregpa** [comment]
I think I got the same type of error
"11/13/2022, 5:52:57 PM ringbridge stopping
11/13/2022, 5:53:02 PM Ring Bridge starting
11/13/2022, 5:53:23 PM Ring Bridge ERROR Error loading plugin "homebridge-ring"
11/13/2022, 5:53:23 PM Ring Bridge WARNING No plugins installed.
11/13/2022, 5:53:23 PM Ring Bridge Loading 1 platforms...
11/13/2022, 5:53:23 PM Ring BridgeBridge is running on port 51836."

And when i go to the Cache it shows no devices have been cashed, where before all the devices in ring were shown there.

**Comment by tonymutschler** [comment]
I uninstalled the plugin and then reinstalled . Same issue

**Comment by AppleMac1976** [comment]
Same experience. Uninstalled and reinstalled the plugin. Logged back into my Ring account. Same "Error loading plugin "homebridge-ring"" error occurred

**Comment by mrosenbergtech** [comment]
Found this in my logs (Eunning HomeBridge Docker Container):
```
[11/13/2022, 7:16:56 PM] ERROR LOADING PLUGIN homebridge-ring:
[11/13/2022, 7:16:56 PM] Error: Cannot find module 'homebridge'
```

**Comment by adsail** [comment]
Same issue here as well. Uninstall/clear npm cache/reinstall did not resolve the issue.

```
[11/13/2022, 9:41:45 PM] ====================
[11/13/2022, 9:41:45 PM] ERROR LOADING PLUGIN homebridge-ring:
[11/13/2022, 9:41:45 PM] Error: Cannot find module 'homebridge'
Require stack:
- /homebridge/node_modules/homebridge-ring/lib/base-accessory.js
- /homebridge/node_modules/homebridge-ring/lib/base-data-accessory.js
- /homebridge/node_modules/homebridge-ring/lib/base-device-accessory.js
- /homebridge/node_modules/homebridge-ring/lib/security-panel.js
- /homebridge/node_modules/homebridge-ring/lib/ring-platform.js
- /homebridge/node_modules/homebridge-ring/lib/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-ring/lib/base-accessory.js:13:21)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
[11/13/2022, 9:41:45 PM] ====================
```

**Comment by cantchooseaname8** [comment]
Same thing happens to me too.

**Comment by bkarakashev** [comment]
same issue for me.

**Comment by AppleMac1976** [comment]
@dgreif Helpful tip for anyone might be experiencing this issue. I was able to restore my HOOBS Box containing the plugin from a backup that plugin version 11.3.1 (which just so happened to be the version I had previously before updating to the latest). According to the logs, the error I encounter previously went away after the restore, and the plugin now works as expected. Perhaps this issue is isolated the latest the version, so maybe restoring to an older version of the plugin if possible might work in the short term, until a fix is pushed for the latest version.

**Comment by AppleMac1976** [comment]
Hmm...interesting. I know the homebridge version I have currently from the backup I restored from was v1.5.0, as opposed to the latest version these days of v1.5.1 (currently running homebridge v1.5.0, node version 16.18.1 and Hoobs version 4.2.8 with the working plugin setup). Could be an issue with how the plugin interacts with newer versions of homebridge perhaps.

**Comment by Stewart06** [comment]
J'ai le même problème depuis la mise à jour vers la dernière version.
Je suis sur HOOBS et tout est jour vers les dernières versions.
J'ai une sonnette Ring Door View Cam, tout fonctionnait bien avant la mise à jour.
Une fois le plugin mise à jour celle-ci à disparue de ma configuration HomeKit et HOOBS n'arrive pas à charger le plugin comme décrit précédemment.

I have the same problem since updating to the latest version.
I'm on HOOBS and everything is up to date with the latest versions.
I have a Ring Door View Cam doorbell, everything was working fine before the update.
Once the plugin was updated, it disappeared from my HomeKit configuration and HOOBS could not load the plugin as described above.

**Comment by AppleMac1976** [comment]
Possible observation. I noticed in the HOOBS system it shows the plugins latest version is 11.5.0, when as far as actual releases go, the latest version is 11.4.0. Maybe this could be something where HOOBS is looking for something with that 11.5.0 version number and is running into problems.

**Comment by Stewart06** [comment]
En tous cas j'ai remis une version ultérieur après avoir désinstallé le plugin et cela fonctionne de nouveau.

In any case I put back a later version after uninstalling the plugin and it works again.

**Comment by davidvanvo** [comment]
11.5.1 update works for me

**Comment by Stewart06** [comment]
YES !!! 👍
