### ISSUE TITLE
API Controller Error After Update to 8.0

### ISSUE THREAD

**Issue by clipse2004** [dgreif/ring#307]
# Bug Report

### Describe the Bug
After updating the Plugin to Version 8.0 I got the following Error:

4.5.2020, 01:23:21 [Ring] Configuring 1 cameras and 2 devices for location "Baiersdorf" - locationId: Xxxxxxxx
4.5.2020, 01:23:21 [Ring] Adding new accessory doorbell_v4 Haustür Ring
4.5.2020, 01:23:21 [Ring] Error connecting to API
4.5.2020, 01:23:21 [Ring] TypeError: accessory.configureController is not a function
    at new Camera (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/homebridge/camera.js:20:19)
    at /home/hoobs/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:188:123
    at Array.forEach (<anonymous>)
    at RingPlatform.<anonymous> (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:167:28)
    at Generator.next (<anonymous>)
    at fulfilled (/home/hoobs/.hoobs/node_modules/homebridge-ring/lib/homebridge/ring-platform.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### To Reproduce
 - Start Homebridge
 - Attempt to ...
 - See error

### Expected behavior
 A clear and concise description of what you expected to happen.

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: [e.g. Raspbian]
 - Node.js: [e.g. 12.14.1] 
 - NPM: [e.g 6.13.4] 
 - homebridge-ring: newest
 - homebridge: newest
- Hoobs -> newest

**Comment by donavanbecker** [comment]
You need to be running homebridge v1.0.0 and higher and currently are hoobs... Install [Homebridge](https://github.com/homebridge/homebridge/wiki).

**Comment by clipse2004** [comment]
I mean the newest hoobs is running Homebridge 1.0

**Comment by Supereg** [comment]
It isn't

**Comment by Supereg** [comment]
Issue can be closed here

**Comment by dgreif** [comment]
Sorry to hear Hoobs hasn’t implemented this properly. Unfortunately it is their responsibility to maintain parity with homebridge if they are going to continue to run their own version of it. I suggest you open an issue on the Hoobs repo requesting that they add bridged camera support.

**Comment by BobbySlope** [comment]
Heres how you can install the Ring Plugin on HOOBS
https://plugins.hoobs.org/plugin/homebridge-ring
is an Workaround while we preparing the Update, once the update is released we will certify the newer version and update the readme
