### ISSUE TITLE
[Streaming]: Ring plug in dies whenever i try to live stream 

### ISSUE THREAD

**Issue by Tesla-P100FX** [dgreif/ring#950]
### Streaming Issue

Hoobs 4.0.104 
Node Version | 16.15.0
Homebridge Version | 1.3.4
RIng 11.0.2

When i try to stream any camera the the ring plug-in quits and restarts 

### Proposed Solution

Dont know 

### Environment

HOOBS

### What operating system are you on?

Linux

### Relevant log output

```shell
Hoobs 4.0.104 
Node Version | 16.15.0
Homebridge Version | 1.3.4

5/24/2022, 9:54:48 AM Ring Bridge Ring Preparing Live Stream for Living Room
5/24/2022, 9:54:49 AM Ring Bridge Ring Stream Prepared for Living Room (0.848s)
5/24/2022, 9:54:49 AM Ring Bridge Ring Activating stream for Living Room (0.955s)
5/24/2022, 9:54:49 AM Ring Bridge [ ERROR ] Error: bind EAFNOSUPPORT ::
    at node:dgram:351:20
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
5/24/2022, 9:54:49 AM Ring Bridge [ ERROR ] Error: bind EAFNOSUPPORT ::
    at node:dgram:351:20
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
5/24/2022, 9:54:49 AM Ring Bridge Ring Stopped Live Stream for Living Room
5/24/2022, 9:54:49 AM Ring Bridge Ring connectionStateChange: closed
5/24/2022, 9:54:49 AM Ring Bridge Ring iceConnectionStateChange: closed
5/24/2022, 9:54:58 AM Camera FFmpeg Bridge Ring Bridge starting
5/24/2022, 9:55:01 AM Ring Bridge [ DEBUG ] Initializing HAP-NodeJS v0.9.4...
5/24/2022, 9:55:03 AM Ring Bridge [ ERROR ] [31mThe plugin "homebridge-ring" requires a Homebridge version of >=1.4.0 which does not satisfy the current Homebridge version of 1.3.4. You may need to update this plugin (or Homebridge) to a newer version. You may face unexpected issues or stability problems running this plugin.[39m
5/24/2022, 9:55:07 AM Ring Bridge Loaded plugin 'homebridge-ring'
5/24/2022, 9:55:07 AM Ring Bridge [ DEBUG ] Registering platform 'homebridge-ring.Ring'
```

### Honesty Time

- [X] I swear this is worth your time!

**Comment by thatsnasty** [comment]
Same here, crashes the bridge too

`Hoobs 4.2.5
Node Version | 16.15.0
Homebridge Version | 1.4.1

25/5/2022, 8:32:42 pmHOOBSRingPreparing Live Stream for Doorbell
25/5/2022, 8:32:44 pmHOOBSRingStream Prepared for Doorbell (1.449s)
25/5/2022, 8:32:44 pmHOOBSRingActivating stream for Doorbell (1.789s)
25/5/2022, 8:32:45 pmHOOBSERRORError: bind EAFNOSUPPORT ::
    at node:dgram:351:20
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
25/5/2022, 8:32:45 pmHOOBSERRORError: bind EAFNOSUPPORT ::
    at node:dgram:351:20
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
25/5/2022, 8:32:45 pmHOOBSRingStopped Live Stream for Doorbell
25/5/2022, 8:32:45 pmHOOBSRingconnectionStateChange: closed
25/5/2022, 8:32:45 pmHOOBSRingiceConnectionStateChange: closed
25/5/2022, 8:32:54 pmHOOBS starting`

**Comment by clickerclacker** [comment]
I'm having the same problem since updating to 11.0.2.

25/05/2022, 12:47:46Ring BridgeERRORError: bind EAFNOSUPPORT ::
    at node:dgram:351:20
    at processTicksAndRejections (node:internal/process/task_queues:84:21)
25/05/2022, 12:47:46Ring BridgeERRORError: bind EAFNOSUPPORT ::
    at node:dgram:351:20
    at processTicksAndRejections (node:internal/process/task_queues:84:21)

**Comment by dgreif** [comment]
Can you give `11.0.3` a try.  Theres no specific fix for this in it, but I did update a lot of the dependencies related to streaming

**Comment by Tesla-P100FX** [comment]
> Can you give `11.0.3` a try.  Theres no specific fix for this in it, but I did update a lot of the dependencies related to streaming

Where can I get 11.0.3. It's not published yet on Hoobs

**Comment by dgreif** [comment]
It's published on npm.  Not sure how often HOOBS syncs these over tho 😞

**Comment by Falc0n2k** [comment]
I'm getting this exact same issue after updating to 11.0.3 on Homebridge. From the logs:

```[29/05/2022, 00:24:23] [homebridge-ring] Preparing Live Stream for Front Door
[29/05/2022, 00:24:23] [homebridge-ring] Stream Prepared for Front Door (0.466s)
[29/05/2022, 00:24:23] [homebridge-ring] Activating stream for Front Door (0.77s)

/usr/local/lib/node_modules/homebridge-ring/node_modules/ice/src/ice.ts:1006
    .map((nic) => {
     ^
TypeError: details.family.toLowerCase is not a function
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/ice/src/ice.ts:1017:26
    at Array.filter (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/ice/src/ice.ts:1015:42
    at Array.map (<anonymous>)
    at nodeIpAddress (/usr/local/lib/node_modules/homebridge-ring/node_modules/ice/src/ice.ts:1006:6)
    at getHostAddresses (/usr/local/lib/node_modules/homebridge-ring/node_modules/ice/src/ice.ts:1038:32)
    at Connection.gatherCandidates (/usr/local/lib/node_modules/homebridge-ring/node_modules/ice/src/ice.ts:86:23)
    at RTCIceGatherer.gather (/usr/local/lib/node_modules/homebridge-ring/node_modules/werift/src/transport/ice.ts:114:29)
    at /usr/local/lib/node_modules/homebridge-ring/node_modules/werift/src/peerConnection.ts:757:38
    at Array.map (<anonymous>)
[29/05/2022, 00:24:26] [homebridge-ring] Child bridge process ended
[29/05/2022, 00:24:26] [homebridge-ring] Process Ended. Code: 1, Signal: null
```

This was working fine under a previous version of the plugin (11.0.2 IIRC), however, a revert back to that or earlier versions doesn't resolve the issue. FWIW, I'm using the latest version of node (18.x.x).

**Comment by dgreif** [comment]
@Falc0n2k I'd recommend trying this on node 16.  18 is latest, but still considered experimental until it is LTS.  You may have the same _symptoms_, but i think the error you are facing is different from the original post.

**Comment by Falc0n2k** [comment]
@dgreif -- You are correct, sir! Reverting to Node 16.15.0 did the trick. I'll be more mindful of this in the future.

**Comment by monroewilliams** [comment]
Another data point: I had the same problem, and reverting to Node 16.15.1 fixed it for me as well.

**Comment by Tesla-P100FX** [comment]
I switched to Scyrpted GitHub - koush/scrypted<https://github.com/koush/scrypted>

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by rnsc** [comment]
Hey, @dgreif I'm having this issue with 11.0.7.
Should I open a new ticket for this?

Hoobs: 4.2.5
Homebridge: 1.4.1
Homebridge ring: 11.0.7
Node: 16.16.0

```raw
18/07/2022, 12:39:22Ring BridgeRingNo snapshot cached for Front Door
18/07/2022, 12:39:22Ring BridgeRingNo snapshot cached for Front Door
18/07/2022, 12:39:22Ring BridgeRingSnapshot cached for Front Door (0.628s)
18/07/2022, 12:39:22Ring BridgeRingSnapshot cached for Front Door (0.628s)
18/07/2022, 12:39:24Ring BridgeRingPreparing Live Stream for Front Door
18/07/2022, 12:39:24Ring BridgeRingPreparing Live Stream for Front Door
18/07/2022, 12:39:25Ring BridgeRingStream Prepared for Front Door (0.91s)
18/07/2022, 12:39:25Ring BridgeRingStream Prepared for Front Door (0.91s)
18/07/2022, 12:39:25Ring BridgeRingActivating stream for Front Door (1.09s)
18/07/2022, 12:39:25Ring BridgeRingActivating stream for Front Door (1.09s)
18/07/2022, 12:39:25Ring BridgeRingWebSocket connected for Front Door
18/07/2022, 12:39:25Ring BridgeRingWebSocket connected for Front Door
18/07/2022, 12:39:26Ring BridgeRingiceConnectionStateChange: completed
18/07/2022, 12:39:26Ring BridgeRingiceConnectionStateChange: completed
18/07/2022, 12:39:27Ring BridgeRingStopped Live Stream for Front Door
18/07/2022, 12:39:27Ring BridgeRingStopped Live Stream for Front Door
18/07/2022, 12:39:27Ring BridgeRingconnectionStateChange: closed
18/07/2022, 12:39:27Ring BridgeRingconnectionStateChange: closed
18/07/2022, 12:39:27Ring BridgeRingiceConnectionStateChange: closed
18/07/2022, 12:39:27Ring BridgeRingiceConnectionStateChange: closed
18/07/2022, 12:39:27Ring BridgeRingCall ended before answered
18/07/2022, 12:39:27Ring BridgeRingCall ended before answered
18/07/2022, 12:39:28Ring BridgeERROR[Ring Bridge 9E7F@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Front Door' was slow to respond!
18/07/2022, 12:39:28Ring BridgeERROR[Ring Bridge 9E7F@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Front Door' was slow to respond!
18/07/2022, 12:39:36Ring Bridge starting
18/07/2022, 12:39:36Ring Bridge starting
[...]
18/07/2022, 12:39:55Ring BridgeERRORRegister request has failed with Error=PHONE_REGISTRATION_ERROR
18/07/2022, 12:39:55Ring BridgeERRORRegister request has failed with Error=PHONE_REGISTRATION_ERROR
18/07/2022, 12:39:55Ring BridgeERRORRetry... 1
18/07/2022, 12:39:55Ring BridgeERRORRetry... 1
18/07/2022, 12:39:56Ring BridgeRingRing connected to socket.io server
18/07/2022, 12:39:56Ring BridgeRingRing connected to socket.io server
```

**Comment by milesjensen** [comment]
I'm having the same issue as well - and it is restarting the bridge each time.  Sometimes I see a frame of the video, but not usually.  AT&T fiber and the ring app works fine.  Not sure what "slow to respond" means, but you can see all the logs are in four seconds, though the connection was closed in two.

Hoobs: 4.2.5
Ring: 11.0.7
Node: 16.16.0

7/22/2022, 4:07:33 PMRing BridgeRingPreparing Live Stream for Front Door
7/22/2022, 4:07:33 PMRing BridgeRingStream Prepared for Front Door (0.706s)
7/22/2022, 4:07:34 PMRing BridgeRingActivating stream for Front Door (0.898s)
7/22/2022, 4:07:34 PMRing BridgeRingWebSocket connected for Front Door
7/22/2022, 4:07:34 PMRing BridgeRingiceConnectionStateChange: completed
7/22/2022, 4:07:35 PMRing BridgeRingStopped Live Stream for Front Door
7/22/2022, 4:07:35 PMRing BridgeRingconnectionStateChange: closed
7/22/2022, 4:07:35 PMRing BridgeRingiceConnectionStateChange: closed
7/22/2022, 4:07:35 PMRing BridgeRingCall ended before answered
7/22/2022, 4:07:37 PMRing BridgeERROR[Ring Bridge 0100@Selected RTP Stream Configuration] The write handler for the characteristic 'Selected RTP Stream Configuration' on the accessory 'Front Door' was slow to respond!
7/22/2022, 4:07:44 PMRing Bridge starting
