### ISSUE TITLE
Error after upgrading to 9.12.3

### ISSUE THREAD

**Issue by malmentm** [dgreif/ring#494]
# Bug Report

### Describe the Bug
After upgrade to 9.12.3 I get this error in log

[11/13/2020, 16:40:27] ERROR LOADING PLUGIN homebridge-ring:
[11/13/2020, 16:40:27] Error: Cannot find module 'socket.io-client'
Require stack:
- /usr/local/lib/node_modules/homebridge-ring/lib/api/location.js
- /usr/local/lib/node_modules/homebridge-ring/lib/api/api.js
- /usr/local/lib/node_modules/homebridge-ring/lib/api/index.js
- /usr/local/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js
- /usr/local/lib/node_modules/homebridge-ring/lib/homebridge/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/location.js:13:28)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
[11/13/2020, 16:40:27] ====================
[11/13/2020, 16:40:27] Loading 2 platforms...
[11/13/2020, 16:40:27] [Config] Initializing config platform...
[11/13/2020, 16:40:27] [Config] Running in Service Mode
[11/13/2020, 16:40:27] Error loading platform requested in your config.json at position 2
[11/13/2020, 16:40:27] Error: The requested platform 'Ring' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:224:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:385:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:80:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
[11/13/2020, 16:40:27] Got SIGTERM, shutting down Homebridge...
[11/13/2020, 16:40:32] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[11/13/2020, 16:40:37] [HB Supervisor] Restarting Homebridge...
[11/13/2020, 16:40:37] [HB Supervisor] Starting Homebridge with extra flags: -I
[11/13/2020, 16:40:37] [HB Supervisor] Started Homebridge v1.2.3 with PID: 1573
[11/13/2020, 16:40:38] Loaded config.json with 5 accessories and 2 platforms.
[11/13/2020, 16:40:38] ---
[11/13/2020, 16:40:39] Loaded plugin: homebridge-config-ui-x@4.32.0
[11/13/2020, 16:40:39] Registering platform 'homebridge-config-ui-x.config'
[11/13/2020, 16:40:39] ---
[11/13/2020, 16:40:39] Loaded plugin: homebridge-http-lightbulb@1.2.0
[11/13/2020, 16:40:39] Registering accessory 'homebridge-http-lightbulb.HTTP-LIGHTBULB'
[11/13/2020, 16:40:39] ---
[11/13/2020, 16:40:40] Loaded plugin: homebridge-http-switch@0.5.31
[11/13/2020, 16:40:40] Registering accessory 'homebridge-http-switch.HTTP-SWITCH'
[11/13/2020, 16:40:40] ---
[11/13/2020, 16:40:40] ====================
[11/13/2020, 16:40:40] ERROR LOADING PLUGIN homebridge-ring:
[11/13/2020, 16:40:40] Error: Cannot find module 'socket.io-client'
Require stack:
- /usr/local/lib/node_modules/homebridge-ring/lib/api/location.js
- /usr/local/lib/node_modules/homebridge-ring/lib/api/api.js
- /usr/local/lib/node_modules/homebridge-ring/lib/api/index.js
- /usr/local/lib/node_modules/homebridge-ring/lib/homebridge/ring-platform.js
- /usr/local/lib/node_modules/homebridge-ring/lib/homebridge/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-ring/lib/api/location.js:13:28)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
[11/13/2020, 16:40:40] ====================

I worked again afterdowngradse to 9.12.2

### To Reproduce
Upgrade to 9.12.3

### Expected behavior
Suppose to work 👍 

### Screenshots/Logs
 If applicable, add screenshots and log output to help explain your problem.

### Additional context
 Add any other context about the problem here.

### Homebridge Ring Config
Post homebridge-ring platform config  _without sensitive information_
```

HIGHLIGHT THIS TEXT AND POST CONFIG HERE
DO NOT INCLUDE YOUR REFRESH TOKEN OR EMAIL/PASSWORD (replace them with xxx)

```

### Environment

 - OS: Homebridge Official Image
 - Node.js: v12.18.4
 - NPM: 6.14.8
 - homebridge-ring: 9.12.3
 - homebridge: 1.2.3
 - hoobs: [e.g. 0.4.50 or N/A]

**Comment by dgreif** [comment]
Fixed in `9.12.4`.  Thanks for reporting.
